FROM golang:1.23 as builder

WORKDIR /app

COPY . .
RUN cd ./service && go mod download && CGO_ENABLED=0 GOOS=linux go build -o app .

FROM alpine:latest

WORKDIR /root/

COPY --from=builder /app/service/app .

CMD ["./app"]
